name: Check for Resonite Updates

on:
  workflow_dispatch:
    inputs:
      force-release:
        description: Force build-release to test build failure when tag already exists
        type: boolean
        required: false
        default: false
  schedule:
  - cron: 37 1/3 * * * #"/3" inicates one check every 3 hours.

jobs:
  check-for-resonite-update:
    runs-on: ubuntu-slim
    outputs:
      UP_TO_DATE: ${{steps.check-version.outputs.UP_TO_DATE}}
      RESONITE_VERSION: ${{steps.check-version.outputs.RESONITE_VERSION}}
    env:
      FORCE_RELEASE: ${{ inputs.force-release }}
      REPOSITORY_NAME: ${{github.repository}}
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: Query Resonite version and check if matching tag exists
      id: check-version
      run: |
        scripts/check-for-resonite-updates.sh #either writes UP_TO_DATE=true or RESONITE_VERSION=x.y.z.b
  trigger-release:
    needs: check-for-resonite-update
    if: needs.check-for-resonite-update.outputs.UP_TO_DATE != 'true'
    permissions:
      contents: write
    uses: $/.github/workflows/build-release.yml
    with:
      description: "Automatic rebuild with Resonite ${{needs.check-for-resonite-update.outputs.RESONITE_VERSION}}"
  mark-failed-release:
    runs-on: ubuntu-slim  
    needs:
    - check-for-resonite-update
    - trigger-release
    if: always() && needs.trigger-release.result == 'failure' #implies not skipped/not up to date
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: Add tag and push
      env:
        FAILED_TAG: failed-${{needs.check-for-resonite-update.outputs.RESONITE_VERSION}}
      run: |
        echo "Marking the workflow run as failed so no further runs are attempted..."
        git tag -f -- "$FAILED_TAG"
        #:refs/tags/... would delete the tag if it already exists in remote.
        git push origin ":refs/tags/$FAILED_TAG"
        #refs/tags/... creates a new one.
        git push origin "refs/tags/$FAILED_TAG"
        exit 100 #fails the workflow

